services:
  sinapsis2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - DOMAIN=${DOMAIN}
    - MYSQL_HOST=${MYSQL_HOST}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DB=${MYSQL_DB}
    ports:
    - "3003:3003"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.sinapsis2-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.sinapsis2-https.tls=true
      - traefik.http.routers.sinapsis2-https.tls.certresolver=le
      - traefik.http.services.sinapsis2.loadbalancer.server.port=3003
    networks:
      - traefik-public
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik-public:
    external: true